<?$APPLICATION->IncludeComponent("bitrix:news.list", "contacts",
	array(
		"IBLOCK_TYPE" => "blocks",
		"IBLOCK_ID" => "#ENEXT_BLOCK_CONTACTS_IBLOCK_ID#",
		"NEWS_COUNT" => "1",
		"SORT_BY1" => "SORT",
		"SORT_ORDER1" => "ASC",
		"SORT_BY2" => "ACTIVE_FROM",
		"SORT_ORDER2" => "DESC",
		"FILTER_NAME" => "",
		"FIELD_CODE" => array(),
		"PROPERTY_CODE" => array(
			0 => "ADDRESS",
			1 => "MAP",
			2 => "TIMEZONE",
			3 => "MON",
			4 => "TUE",
			5 => "WED",
			6 => "THU",
			7 => "FRI",
			8 => "SAT",
			9 => "SUN",
			10 => "PHONE",			
			11 => "WHATSAPP",
			12 => "VIBER",
			13 => "TELEGRAM",
			14 => "INSTAGRAM",
			15 => "EMAIL",
			16 => "SKYPE",
		),
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"AJAX_MODE" => "",
		"AJAX_OPTION_SHADOW" => "",
		"AJAX_OPTION_JUMP" => "",
		"AJAX_OPTION_STYLE" => "",
		"AJAX_OPTION_HISTORY" => "",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "Y",
		"PREVIEW_TRUNCATE_LEN" => "",
		"ACTIVE_DATE_FORMAT" => "",
		"DISPLAY_PANEL" => "",
		"SET_TITLE" => "N",
		"SET_STATUS_404" => "N",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"DISPLAY_NAME" => "",
		"DISPLAY_DATE" => "",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"PAGER_SHOW_ALWAYS" => "",
		"PAGER_TEMPLATE" => "",
		"PAGER_DESC_NUMBERING" => "",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "",
		"PAGER_SHOW_ALL" => "",
		"AJAX_OPTION_ADDITIONAL" => "",
		"OBJECTS_IBLOCK_TYPE" => "content",
		"OBJECTS_IBLOCK_ID" => "#ENEXT_OBJECTS_IBLOCK_ID#"
	),
	false
);?>