<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Корзина");?>

<?$APPLICATION->IncludeComponent("altop:sale.basket.basket", ".default", 
	array(
		"PATH_TO_ORDER" => "/personal/order/make/",
		"HIDE_COUPON" => "N",
		"COLUMNS_LIST_EXT" => array(
			0 => "NAME",
			1 => "DISCOUNT",
			2 => "PROPS",
			3 => "DELETE",
			4 => "DELAY",
			5 => "PRICE",
			6 => "QUANTITY",
			7 => "SUM",
			8 => "PROPERTY_ARTNUMBER",
			9 => "PROPERTY_CML2_ARTICLE",
			10 => "PROPERTY_OBJECT",
			11 => "PROPERTY_M2_COUNT",
			12 => "PROPERTY_OLD_PRICE",
		),
		"PRICE_VAT_SHOW_VALUE" => "N",
		"USE_PREPAYMENT" => "Y",
		"QUANTITY_FLOAT" => "Y",
		"CORRECT_RATIO" => "N",
		"AUTO_CALCULATION" => "Y",
		"SET_TITLE" => "Y",
		"ACTION_VARIABLE" => "basketAction",
		"COMPATIBLE_MODE" => "Y",
		"USE_GIFTS" => "Y",
		"GIFTS_PAGE_ELEMENT_COUNT" => "4",
		"GIFTS_BLOCK_TITLE" => "Выберите один из подарков",
		"GIFTS_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_TEXT_LABEL_GIFT" => "Подарок",
		"GIFTS_MESS_BTN_BUY" => "Выбрать",
		"CATALOG_IBLOCK_TYPE" => "catalog",
		"CATALOG_IBLOCK_ID" => "26",
		"CATALOG_INCLUDE_SUBSECTIONS" => "Y",
		"CATALOG_HIDE_NOT_AVAILABLE" => "N",
		"CATALOG_HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"CATALOG_ELEMENT_SORT_FIELD" => "sort",
		"CATALOG_ELEMENT_SORT_ORDER" => "asc",
		"CATALOG_ELEMENT_SORT_FIELD2" => "id",
		"CATALOG_ELEMENT_SORT_ORDER2" => "desc",
		"CATALOG_OFFERS_SORT_FIELD" => "sort",
		"CATALOG_OFFERS_SORT_ORDER" => "asc",
		"CATALOG_OFFERS_SORT_FIELD2" => "id",
		"CATALOG_OFFERS_SORT_ORDER2" => "desc",
		"CATALOG_PROPERTY_CODE" => array(),		
		"CATALOG_OFFERS_FIELD_CODE" => array(
			0 => "NAME",
		),
		"CATALOG_OFFERS_PROPERTY_CODE" => array(
			0 => "COLOR_REF",
			1 => "SIZE",
		),
		"CATALOG_OFFERS_LIMIT" => "0",
		"CATALOG_PRODUCT_DISPLAY_MODE" => "Y",		
		"CATALOG_OFFER_TREE_PROPS" => array(
			0 => "COLOR_REF",
			1 => "SIZE",
		),
		"CATALOG_PRODUCT_SUBSCRIPTION" => "Y",
		"CATALOG_SHOW_DISCOUNT_PERCENT" => "Y",		
		"CATALOG_SHOW_OLD_PRICE" => "Y",
		"CATALOG_SHOW_MAX_QUANTITY" => "M",
		"CATALOG_MESS_SHOW_MAX_QUANTITY" => "В наличии",
		"CATALOG_RELATIVE_QUANTITY_FACTOR" => "5",
		"CATALOG_MESS_RELATIVE_QUANTITY_MANY" => "много",
		"CATALOG_MESS_RELATIVE_QUANTITY_FEW" => "мало",		
		"CATALOG_MESS_BTN_BUY" => "Купить",
		"CATALOG_MESS_BTN_ADD_TO_BASKET" => "Купить",
		"CATALOG_MESS_BTN_SUBSCRIBE" => "Сообщить о поступлении",
		"CATALOG_MESS_BTN_DETAIL" => "Подробнее",
		"CATALOG_MESS_NOT_AVAILABLE" => "Нет в наличии",
		"CATALOG_USE_MAIN_ELEMENT_SECTION" => "N",
		"CATALOG_PRICE_CODE" => array(
			0 => "BASE",
		),
		"CATALOG_USE_PRICE_COUNT" => "Y",
		"CATALOG_SHOW_PRICE_COUNT" => "1",
		"CATALOG_PRICE_VAT_INCLUDE" => "Y",
		"CATALOG_CONVERT_CURRENCY" => "N",		
		"CATALOG_CURRENCY_ID" => "",
		"CATALOG_BASKET_URL" => "/personal/cart/",
		"CATALOG_USE_PRODUCT_QUANTITY" => "Y",
		"CATALOG_ADD_PROPERTIES_TO_BASKET" => "Y",
		"CATALOG_PARTIAL_PRODUCT_PROPERTIES" => "Y",
		"CATALOG_PRODUCT_PROPERTIES" => array(
			0 => "SIZE_LIST",
		),
		"CATALOG_OFFERS_CART_PROPERTIES" => array(
			0 => "COLOR_REF",
			1 => "SIZE",
		),
		"CATALOG_ADD_TO_BASKET_ACTION" => "ADD",
		"CATALOG_USE_REVIEW" => "Y",
		"CATALOG_REVIEWS_IBLOCK_TYPE" => "reviews",
		"CATALOG_REVIEWS_IBLOCK_ID" => "34",
		"CATALOG_REVIEWS_NEWS_COUNT" => "5",
		"CATALOG_REVIEWS_SORT_BY1" => "SORT",
		"CATALOG_REVIEWS_SORT_ORDER1" => "ASC",
		"CATALOG_REVIEWS_SORT_BY2" => "ACTIVE_FROM",
		"CATALOG_REVIEWS_SORT_ORDER2" => "DESC",
		"CATALOG_REVIEWS_ACTIVE_DATE_FORMAT" => "j F Y",
		"CATALOG_REVIEWS_PROPERTY_CODE" => array(
			0 => "RATING",
			1 => "FILES",
			2 => "TERM",
			3 => "RECOMMEND",
			4 => "ADVANTAGES",
			5 => "DEFECTS",
			6 => "COMMENT",
			7 => "NAME",
			8 => "USER_ID",
			9 => "CITY",
			10 => "LIKES",
		),
		"CATALOG_MESS_REVIEWS_TAB" => "Отзывы",
		"CATALOG_DISPLAY_COMPARE" => "Y",
		"CATALOG_COMPARE_PATH" => "/catalog/compare/",
		"CATALOG_MESS_BTN_COMPARE" => "Добавить к сравнению",
		"CATALOG_COMPARE_NAME" => "CATALOG_COMPARE_LIST",
		"CATALOG_DETAIL_ADD_PICT_PROP" => "MORE_PHOTO",
		"CATALOG_DETAIL_OFFER_ADD_PICT_PROP" => "MORE_PHOTO",
		"CATALOG_DETAIL_PROPERTY_CODE" => array(
			0 => "ARTNUMBER",
			1 => "BRAND",
			2 => "COLLECTION",
			3 => "COUNTRY",			
			4 => "POWER",
			5 => "MAX_TORQUE",			
			6 => "COLORS_REF",			
			7 => "LENGTH",
			8 => "HEIGHT",
			9 => "WIDTH",
			10 => "WEIGHT",			
			11 => "PROP07",
			12 => "PROP08",
			13 => "PROP09",
			14 => "PROP10",
			15 => "PROP11",
			16 => "PROP12",
			17 => "PROP13",
			18 => "PROP14",
			19 => "PROP15",
			20 => "PROP16",
			21 => "PROP17",
			22 => "PROP18",
			23 => "PROP19",
			24 => "M2_COUNT",
			25 => "PROP22",
			26 => "PROP23",
			27 => "PROP24",
			28 => "PROP25",
			29 => "PROP26",
			30 => "PROP27",
			31 => "PROP28",
			32 => "PROP29",
		),				
		"CATALOG_DETAIL_OFFERS_FIELD_CODE" => array(
			0 => "NAME",
			1 => "TIMESTAMP_X",
		),
		"CATALOG_DETAIL_OFFERS_PROPERTY_CODE" => array(
			0 => "COLOR_REF",
			1 => "SIZE",
		),
		"CATALOG_DETAIL_MAIN_BLOCK_PROPERTY_CODE" => array(		
			0 => "BRAND",
			1 => "COLLECTION",
			2 => "POWER",
			3 => "MAX_TORQUE",
			4 => "WEIGHT",			
			5 => "PROP08",
			6 => "PROP09",
			7 => "PROP15",
			8 => "PROP17",
			9 => "M2_COUNT",
			10 => "PROP22",
			11 => "PROP23",
			12 => "PROP24",
			13 => "PROP27",
			14 => "PROP28",
			15 => "PROP29",	
		),
		"CATALOG_DETAIL_MAIN_BLOCK_OFFERS_PROPERTY_CODE" => array(),	
		"CATALOG_DETAIL_IMAGE_RESOLUTION" => "16by9",				
		"CATALOG_DETAIL_ADD_DETAIL_TO_SLIDER" => "Y",
		"CATALOG_DETAIL_DETAIL_PICTURE_MODE" => array(
			0 => "POPUP",
			1 => "MAGNIFIER",
		),
		"CATALOG_DETAIL_SHOW_SLIDER" => "N",
		"CATALOG_DETAIL_SLIDER_INTERVAL" => "",
		"CATALOG_DETAIL_SLIDER_PROGRESS" => "",
		"CATALOG_USE_GIFTS_DETAIL" => "Y",
		"CATALOG_GIFTS_DETAIL_PAGE_ELEMENT_COUNT" => "5",
		"CATALOG_GIFTS_DETAIL_HIDE_BLOCK_TITLE" => "N",
		"CATALOG_GIFTS_DETAIL_BLOCK_TITLE" => "Выберите один из подарков к этому товару",
		"CATALOG_GIFTS_DETAIL_TEXT_LABEL_GIFT" => "Подарок",
		"CATALOG_GIFTS_MESS_BTN_BUY" => "Выбрать",
		"CATALOG_USE_STORE" => "N",
		"CATALOG_STORE_PATH" => "",
		"CATALOG_STORES" => array(),
		"CATALOG_USE_MIN_AMOUNT" => "Y",
		"CATALOG_USER_FIELDS" => array(
			0 => "UF_OBJECT",
		),
		"CATALOG_FIELDS" => array(
			0 => "TITLE",
			1 => "ADDRESS",
			2 => "DESCRIPTION",
			3 => "PHONE",
			4 => "SCHEDULE",
			5 => "EMAIL",
			6 => "IMAGE_ID",
		),
		"CATALOG_MIN_AMOUNT" => "5",
		"CATALOG_SHOW_EMPTY_STORE" => "Y",
		"CATALOG_SHOW_GENERAL_STORE_INFORMATION" => "N",
		"CATALOG_MAIN_TITLE" => "Наличие в магазинах",
		"CATALOG_SET_ITEMS_COUNT" => "3",
		"OBJECTS_USE_REVIEW" => "Y",
		"OBJECTS_REVIEWS_IBLOCK_TYPE" => "reviews",
		"OBJECTS_REVIEWS_IBLOCK_ID" => "22",
		"CONTACTS_IBLOCK_TYPE" => "blocks",
		"CONTACTS_IBLOCK_ID" => "6",
		"CONTACTS_USE_REVIEW" => "Y",
		"CONTACTS_REVIEWS_IBLOCK_TYPE" => "reviews",
		"CONTACTS_REVIEWS_IBLOCK_ID" => "21",
		"CONTACTS_REVIEWS_PAGE_LINK" => "/about/reviews/",
		"OFFERS_PROPS" => array(
			0 => "COLOR_REF",
			1 => "SIZE",
		),
		"USE_ENHANCED_ECOMMERCE" => "N",
	),
	false
);?>

<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>