<?$APPLICATION->IncludeComponent("bitrix:news.list", "block_slider",
	array(
		"IBLOCK_TYPE" => "blocks",
		"IBLOCK_ID" => "7",
		"NEWS_COUNT" => "10",
		"SORT_BY1" => "SORT",
		"SORT_ORDER1" => "ASC",
		"SORT_BY2" => "ACTIVE_FROM",
		"SORT_ORDER2" => "DESC",
		"FILTER_NAME" => "",
		"FIELD_CODE" => array(),
		"PROPERTY_CODE" => array(
			0 => "SHOW_NAME",
			1 => "ALIGN",
			2 => "VERTICAL_ALIGN",
			3 => "URL",
			4 => "BUTTON_1_TEXT",
			5 => "BUTTON_1_URL",
			6 => "BUTTON_2_TEXT",
			7 => "BUTTON_2_URL",
			8 => "BUTTON_3_TEXT",
			9 => "BUTTON_3_URL",
			10 => "BUTTON_4_TEXT",
			11 => "BUTTON_4_URL",
			12 => "VIDEO",
			13 => "VIDEO_WIDTH",
			14 => "VIDEO_HEIGHT"
		),
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"AJAX_MODE" => "",
		"AJAX_OPTION_SHADOW" => "",
		"AJAX_OPTION_JUMP" => "",
		"AJAX_OPTION_STYLE" => "",
		"AJAX_OPTION_HISTORY" => "",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "Y",
		"PREVIEW_TRUNCATE_LEN" => "",
		"ACTIVE_DATE_FORMAT" => "",
		"DISPLAY_PANEL" => "",
		"SET_TITLE" => "N",
		"SET_STATUS_404" => "N",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"DISPLAY_NAME" => "",
		"DISPLAY_DATE" => "",
		"DISPLAY_TOP_PAGER" => "",
		"DISPLAY_BOTTOM_PAGER" => "",
		"PAGER_SHOW_ALWAYS" => "",
		"PAGER_TEMPLATE" => "",
		"PAGER_DESC_NUMBERING" => "",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "",
		"PAGER_SHOW_ALL" => "",
		"AJAX_OPTION_ADDITIONAL" => ""
	),
	false
);?>