<?$APPLICATION->IncludeComponent("bitrix:catalog.products.viewed", ".default", 
	array(
		"COMPONENT_TEMPLATE" => ".default",
		"IBLOCK_MODE" => "single",
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "26",
		"SHOW_FROM_SECTION" => "N",
		"SECTION_ID" => "",
		"SECTION_CODE" => "",
		"SECTION_ELEMENT_ID" => "",
		"SECTION_ELEMENT_CODE" => "",
		"DEPTH" => "2",
		"HIDE_NOT_AVAILABLE" => "N",
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"PAGE_ELEMENT_COUNT" => "12",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_GROUPS" => "Y",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"ACTION_VARIABLE" => "action_cpv",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRICE_CODE" => array(),
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"CONVERT_CURRENCY" => "N",
		"BASKET_URL" => "/personal/cart/",
		"USE_PRODUCT_QUANTITY" => "N",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"DISPLAY_COMPARE" => "N",
		"PROPERTY_CODE_26" => array(),
		"CART_PROPERTIES_26" => array(),
		"ADDITIONAL_PICT_PROP_26" => "-",
		"LABEL_PROP_26" => array(),
		"PROPERTY_CODE_27" => array(),
		"CART_PROPERTIES_27" => array(),
		"ADDITIONAL_PICT_PROP_27" => "-",
		"OFFER_TREE_PROPS_27" => array()
	),
	false
);?>