<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("description", "Каталог брендов и производителей | Интернет-магазин медицинского оборудования Офтальмаг");
$APPLICATION->SetPageProperty("title", "Бренды и производители | Интернет-магазин медицинского оборудования Офтальмаг");
$APPLICATION->SetTitle("Бренды и производители");?>

<?
	$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"brands", 
	array(
		"DISPLAY_DATE" => "",
		"DISPLAY_PICTURE" => "",
		"DISPLAY_PREVIEW_TEXT" => "",
		"SEF_MODE" => "Y",
		"AJAX_MODE" => "N",
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "23",
		"NEWS_COUNT" => "48",
		"USE_SEARCH" => "N",
		"USE_RSS" => "N",
		"USE_RATING" => "N",
		"USE_CATEGORIES" => "N",
		"USE_REVIEW" => "N",
		"USE_FILTER" => "Y",
		"SORT_BY1" => "SORT",
		"SORT_ORDER1" => "ASC",
		"SORT_BY2" => "ACTIVE_FROM",
		"SORT_ORDER2" => "DESC",
		"CHECK_DATES" => "Y",
		"PREVIEW_TRUNCATE_LEN" => "",
		"LIST_ACTIVE_DATE_FORMAT" => "",
		"LIST_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "MARKER",
			1 => "COUNTRY",
			2 => "",
		),
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"DISPLAY_NAME" => "N",
		"META_KEYWORDS" => "META_KEYWORDS",
		"META_DESCRIPTION" => "META_DESCRIPTION",
		"BROWSER_TITLE" => "BROWSER_TITLE",
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DETAIL_ACTIVE_DATE_FORMAT" => "",
		"DETAIL_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_PROPERTY_CODE" => array(
			0 => "MARKER",
			1 => "COUNTRY",
			2 => "",
		),
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "N",
		"DETAIL_PAGER_TITLE" => "",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_SHOW_ALL" => "N",
		"SET_TITLE" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"ADD_ELEMENT_CHAIN" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SET_STATUS_404" => "Y",
		"SHOW_404" => "N",
		"MESSAGE_404" => "",
		"PAGER_BASE_LINK" => "",
		"PAGER_PARAMS_NAME" => "",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"USE_PERMISSIONS" => "N",
		"GROUP_PERMISSIONS" => "",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Бренды и производители",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "arrows",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "",
		"PAGER_SHOW_ALL" => "N",
		"FILTER_NAME" => "arBrandsFilter",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"NUM_NEWS" => "",
		"NUM_DAYS" => "",
		"YANDEX" => "",
		"MAX_VOTE" => "",
		"VOTE_NAMES" => "",
		"CATEGORY_IBLOCK" => "",
		"CATEGORY_CODE" => "",
		"CATEGORY_ITEMS_COUNT" => "",
		"MESSAGES_PER_PAGE" => "",
		"USE_CAPTCHA" => "",
		"REVIEW_AJAX_POST" => "",
		"PATH_TO_SMILE" => "",
		"FORUM_ID" => "",
		"URL_TEMPLATES_READ" => "",
		"SHOW_LINK_TO_FORUM" => "",
		"POST_FIRST_MESSAGE" => "",
		"SEF_FOLDER" => "/brands/",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"USE_SHARE" => "",
		"SHARE_HIDE" => "",
		"SHARE_TEMPLATE" => "",
		"SHARE_HANDLERS" => "",
		"SHARE_SHORTEN_URL_LOGIN" => "",
		"SHARE_SHORTEN_URL_KEY" => "",
		"COMPONENT_TEMPLATE" => "brands",
		"AJAX_OPTION_ADDITIONAL" => "",
		"INCLUDE_SUBSECTIONS" => "N",
		"SHOW_COLLECTIONS" => "Y",
		"COLLECTIONS_IBLOCK_TYPE" => "catalog",
		"COLLECTIONS_IBLOCK_ID" => "24",
		"COLLECTIONS_NEWS_COUNT" => "8",
		"COLLECTIONS_SORT_BY1" => "SORT",
		"COLLECTIONS_SORT_ORDER1" => "ASC",
		"COLLECTIONS_SORT_BY2" => "ACTIVE_FROM",
		"COLLECTIONS_SORT_ORDER2" => "DESC",
		"COLLECTIONS_PROPERTY_CODE" => array(
			0 => "BRAND",
			1 => "MARKER",
			2 => "COLORS",
			3 => "MORE_PHOTO",
			4 => "",
		),
		"COLLECTIONS_SHOW_MIN_PRICE" => "Y",
		"CATALOG_IBLOCK_TYPE" => "catalog",
		"CATALOG_IBLOCK_ID" => "26",
		"CATALOG_INCLUDE_SUBSECTIONS" => "Y",
		"CATALOG_HIDE_NOT_AVAILABLE" => "N",
		"CATALOG_HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"CATALOG_ELEMENT_SORT_FIELD" => "sort",
		"CATALOG_ELEMENT_SORT_ORDER" => "asc",
		"CATALOG_ELEMENT_SORT_FIELD2" => "id",
		"CATALOG_ELEMENT_SORT_ORDER2" => "desc",
		"CATALOG_OFFERS_SORT_FIELD" => "sort",
		"CATALOG_OFFERS_SORT_ORDER" => "asc",
		"CATALOG_OFFERS_SORT_FIELD2" => "id",
		"CATALOG_OFFERS_SORT_ORDER2" => "desc",
		"CATALOG_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"CATALOG_OFFERS_FIELD_CODE" => array(
			0 => "NAME",
			1 => "",
		),
		"CATALOG_OFFERS_PROPERTY_CODE" => array(
			0 => "COLOR_REF",
			1 => "SIZE",
			2 => "",
		),
		"CATALOG_OFFERS_LIMIT" => "0",
		"CATALOG_PRODUCT_DISPLAY_MODE" => "Y",
		"CATALOG_OFFER_TREE_PROPS" => array(
			0 => "COLOR_REF",
			1 => "SIZE",
		),
		"CATALOG_PRODUCT_SUBSCRIPTION" => "Y",
		"CATALOG_SHOW_DISCOUNT_PERCENT" => "Y",
		"CATALOG_SHOW_OLD_PRICE" => "Y",
		"CATALOG_SHOW_MAX_QUANTITY" => "M",
		"CATALOG_MESS_SHOW_MAX_QUANTITY" => "В наличии",
		"CATALOG_RELATIVE_QUANTITY_FACTOR" => "5",
		"CATALOG_MESS_RELATIVE_QUANTITY_MANY" => "много",
		"CATALOG_MESS_RELATIVE_QUANTITY_FEW" => "мало",
		"CATALOG_MESS_BTN_BUY" => "Купить",
		"CATALOG_MESS_BTN_ADD_TO_BASKET" => "Купить",
		"CATALOG_MESS_BTN_SUBSCRIBE" => "Сообщить о поступлении",
		"CATALOG_MESS_BTN_DETAIL" => "Подробнее",
		"CATALOG_MESS_NOT_AVAILABLE" => "Нет в наличии",
		"CATALOG_USE_MAIN_ELEMENT_SECTION" => "N",
		"CATALOG_PRICE_CODE" => array(
			0 => "BASE",
		),
		"CATALOG_USE_PRICE_COUNT" => "Y",
		"CATALOG_SHOW_PRICE_COUNT" => "1",
		"CATALOG_PRICE_VAT_INCLUDE" => "Y",
		"CATALOG_CONVERT_CURRENCY" => "N",
		"CATALOG_CURRENCY_ID" => "",
		"CATALOG_DETAIL_USE_RATIO_IN_RANGES" => "N",
		"CATALOG_BASKET_URL" => "/personal/cart/",
		"CATALOG_USE_PRODUCT_QUANTITY" => "Y",
		"CATALOG_ADD_PROPERTIES_TO_BASKET" => "Y",
		"CATALOG_PARTIAL_PRODUCT_PROPERTIES" => "Y",
		"CATALOG_PRODUCT_PROPERTIES" => array(
		),
		"CATALOG_OFFERS_CART_PROPERTIES" => array(
			0 => "COLOR_REF",
			1 => "SIZE",
		),
		"CATALOG_ADD_TO_BASKET_ACTION" => "ADD",
		"CATALOG_USE_REVIEW" => "Y",
		"CATALOG_REVIEWS_IBLOCK_TYPE" => "reviews",
		"CATALOG_REVIEWS_IBLOCK_ID" => "34",
		"CATALOG_REVIEWS_NEWS_COUNT" => "5",
		"CATALOG_REVIEWS_SORT_BY1" => "SORT",
		"CATALOG_REVIEWS_SORT_ORDER1" => "ASC",
		"CATALOG_REVIEWS_SORT_BY2" => "ACTIVE_FROM",
		"CATALOG_REVIEWS_SORT_ORDER2" => "DESC",
		"CATALOG_REVIEWS_ACTIVE_DATE_FORMAT" => "j F Y",
		"CATALOG_REVIEWS_PROPERTY_CODE" => array(
			0 => "RATING",
			1 => "TERM",
			2 => "RECOMMEND",
			3 => "ADVANTAGES",
			4 => "DEFECTS",
			5 => "COMMENT",
			6 => "NAME",
			7 => "USER_ID",
			8 => "CITY",
			9 => "LIKES",
			10 => "FILES",
			11 => "",
		),
		"CATALOG_MESS_REVIEWS_TAB" => "Отзывы",
		"CATALOG_DISPLAY_COMPARE" => "Y",
		"CATALOG_COMPARE_PATH" => "/catalog/compare/",
		"CATALOG_MESS_BTN_COMPARE" => "Добавить к сравнению",
		"CATALOG_COMPARE_NAME" => "CATALOG_COMPARE_LIST",
		"CATALOG_DETAIL_ADD_PICT_PROP" => "MORE_PHOTO",
		"CATALOG_DETAIL_OFFER_ADD_PICT_PROP" => "MORE_PHOTO",
		"CATALOG_DETAIL_PROPERTY_CODE" => array(
			0 => "",
			1 => "ARTNUMBER",
			2 => "BRAND",
			3 => "COLLECTION",
			4 => "COUNTRY",
			5 => "POWER",
			6 => "MAX_TORQUE",
			7 => "COLORS_REF",
			8 => "LENGTH",
			9 => "HEIGHT",
			10 => "WIDTH",
			11 => "WEIGHT",
			12 => "PROP07",
			13 => "PROP08",
			14 => "PROP09",
			15 => "PROP10",
			16 => "PROP11",
			17 => "PROP12",
			18 => "PROP13",
			19 => "PROP14",
			20 => "PROP15",
			21 => "PROP16",
			22 => "PROP17",
			23 => "PROP18",
			24 => "PROP19",
			25 => "M2_COUNT",
			26 => "PROP22",
			27 => "PROP23",
			28 => "PROP24",
			29 => "PROP25",
			30 => "PROP26",
			31 => "PROP27",
			32 => "PROP28",
			33 => "PROP29",
			34 => "",
		),
		"CATALOG_DETAIL_OFFERS_FIELD_CODE" => array(
			0 => "NAME",
			1 => "TIMESTAMP_X",
			2 => "",
		),
		"CATALOG_DETAIL_OFFERS_PROPERTY_CODE" => array(
			0 => "COLOR_REF",
			1 => "SIZE",
			2 => "",
		),
		"CATALOG_DETAIL_MAIN_BLOCK_PROPERTY_CODE" => array(
		),
		"CATALOG_DETAIL_MAIN_BLOCK_OFFERS_PROPERTY_CODE" => array(
		),
		"CATALOG_DETAIL_IMAGE_RESOLUTION" => "16by9",
		"CATALOG_DETAIL_ADD_DETAIL_TO_SLIDER" => "Y",
		"CATALOG_DETAIL_DETAIL_PICTURE_MODE" => array(
			0 => "POPUP",
			1 => "MAGNIFIER",
		),
		"CATALOG_DETAIL_SHOW_SLIDER" => "N",
		"CATALOG_DETAIL_SLIDER_INTERVAL" => "",
		"CATALOG_DETAIL_SLIDER_PROGRESS" => "",
		"CATALOG_USE_GIFTS_DETAIL" => "Y",
		"CATALOG_GIFTS_DETAIL_PAGE_ELEMENT_COUNT" => "5",
		"CATALOG_GIFTS_DETAIL_HIDE_BLOCK_TITLE" => "N",
		"CATALOG_GIFTS_DETAIL_BLOCK_TITLE" => "Выберите один из подарков к этому товару",
		"CATALOG_GIFTS_DETAIL_TEXT_LABEL_GIFT" => "Подарок",
		"CATALOG_GIFTS_MESS_BTN_BUY" => "Выбрать",
		"CATALOG_USE_STORE" => "N",
		"CATALOG_STORE_PATH" => "",
		"CATALOG_STORES" => "",
		"CATALOG_USE_MIN_AMOUNT" => "Y",
		"CATALOG_USER_FIELDS" => array(
			0 => "UF_OBJECT",
		),
		"CATALOG_FIELDS" => array(
			0 => "TITLE",
			1 => "ADDRESS",
			2 => "DESCRIPTION",
			3 => "PHONE",
			4 => "SCHEDULE",
			5 => "EMAIL",
			6 => "IMAGE_ID",
		),
		"CATALOG_MIN_AMOUNT" => "5",
		"CATALOG_SHOW_EMPTY_STORE" => "Y",
		"CATALOG_SHOW_GENERAL_STORE_INFORMATION" => "N",
		"CATALOG_MAIN_TITLE" => "Наличие в магазинах",
		"CATALOG_SET_ITEMS_COUNT" => "3",
		"OBJECTS_USE_REVIEW" => "Y",
		"OBJECTS_REVIEWS_IBLOCK_TYPE" => "reviews",
		"OBJECTS_REVIEWS_IBLOCK_ID" => "22",
		"CONTACTS_IBLOCK_TYPE" => "blocks",
		"CONTACTS_IBLOCK_ID" => "6",
		"CONTACTS_USE_REVIEW" => "Y",
		"CONTACTS_REVIEWS_IBLOCK_TYPE" => "reviews",
		"CONTACTS_REVIEWS_IBLOCK_ID" => "21",
		"CONTACTS_REVIEWS_PAGE_LINK" => "/about/reviews/",
		"STRICT_SECTION_CHECK" => "N",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "",
			"detail" => "#ELEMENT_CODE#/",
		)
	),
	false
);?>

<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>